server:
  port: 0

spring:
  application:
    name: @project.name@
    version: @project.version@
    description: @project.description@

  datasource:
    url: jdbc:mysql://localhost:3306/task-bot-db
    username: root
    password: pass
#    url: jdbc:mysql://${DB_HOST:mysqldb:3306}/${DB_NAME:task-bot-db}?createDatabaseIfNotExist=true
#    username: ${DB_USER:root}
#    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

telegram-bot:
  name: mrkevr_task_bot
  token: 7244417148:AAEEdzGkGuETk8l-yVG5rvu6_asaTmfSbvg
